### ISSUE TITLE
Estabelecer convenção de código a ser utilizada

### ISSUE THREAD

**Issue by leobalter** [mozillabrasil/corsac#13]
Antes que fique super difícil de manter, vamos estabelecer uma convenção de código? 

jQuery ou Idiomatic são as minhas duas sugestões, mas elas doem pra quem não está acostumado ainda. :)

**Comment by cstipkovic** [comment]
idiomatic eu não conheço, jquery eu uso no dia a dia, mas o que vcs decidirem eu to dentro :)

**Comment by leobalter** [comment]
a convenção do jQuery é muito similar ao Idiomatic, com regras mais específicas, como uso de `"` invés de `'`, uma linha em branco acima de qualquer comentário, tabs invés de espaços, etc.

A gente precisa na verdade é escolher (precisa ser algo que todos concordem), apontar pra convenção e nesse caso adaptar o .editorconfig (eu particularmente não costumo usar, é responsabilidade do colaborador).

Referencias: 
- [IdiomaticJS](https://github.com/rwaldron/idiomatic.js)
- [jQuery Style Guide](http://contribute.jquery.org/style-guide/js/)
- [B2G Gaia](https://developer.mozilla.org/en-US/Firefox_OS/Platform/Gaia/Hacking#Coding_style_basics)
