### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by leobalter** [mozillabrasil/corsac#15]
@soapdog, poderia me indicar exemplos de utilização do corsac de todas as features?

Vou experimentar ela aqui, mas a ideia central é criar testes e fazer push. 

[]s!

**Comment by cstipkovic** [comment]
@leobalter, ta pensando em usar o que para os teste (só curiosidade mesmo)? :)

**Comment by leobalter** [comment]
o próprio NPM, gerar scripts pra executar os comandos principais e cuspir
resultados de falhas/acertos.

2014-01-28 Clauber Stipkovic notifications@github.com
